name: socks5_proxy
version: 2.0.0
description: Socks5 server and client with ability to catch packet in both direction, chain proxies and more.
repository: https://github.com/LacticWhale/socks_dart

environment:
  sdk: '>=3.7.0 <4.0.0'

dev_dependencies:
  test: 
  zekfad_lints: 

dependencies:
  async: 
  meta: 
