name: socks_proxy
version: 1.0.0
description: Socks5 server and client with ability to catch packet in both direction, chain proxies and more.
repository: https://github.com/LacticWhale/socks_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  zekfad_lints: ^1.1.0
dependencies: 
  async: ^2.9.0
  meta: ^1.8.0

